
--Q1. What is the total revenue generated by male vs. female customers?
SELECT
    gender,
    SUM("purchase_amount_(usd)") AS total_revenue
FROM customer
GROUP BY gender;


--Q2. Which customers used a discount but still spent more than the average purchase amount? 
SELECT
    customer_id,
    gender,
    age,
    item_purchased,
    "purchase_amount_(usd)" AS purchase_amount,
    discount_applied
FROM customer
WHERE discount_applied = 'Yes'
  AND "purchase_amount_(usd)" >
      (
          SELECT AVG("purchase_amount_(usd)")
          FROM customer
      );
	  

-- Q3. Which are the top 5 products with the highest average review rating?
SELECT
    item_purchased,
    ROUND(AVG(review_rating)::numeric, 2) AS avg_review_rating
FROM customer
GROUP BY item_purchased
ORDER BY avg_review_rating DESC
LIMIT 5;


--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
SELECT
    shipping_type,
    ROUND(AVG("purchase_amount_(usd)"), 2) AS avg_purchase_amount
FROM customer
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;


--Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
SELECT
    subscription_status,
    ROUND(AVG("purchase_amount_(usd)"), 2) AS avg_spend,
    SUM("purchase_amount_(usd)") AS total_revenue
FROM customer
GROUP BY subscription_status;


--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT
    item_purchased,
    ROUND(
        100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)
        / COUNT(*),
        2
    ) AS discount_percentage
FROM customer
GROUP BY item_purchased
ORDER BY discount_percentage DESC
LIMIT 5;


--Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment. 
SELECT
    CASE
        WHEN previous_purchases <= 5 THEN 'New'
        WHEN previous_purchases BETWEEN 6 AND 20 THEN 'Returning'
        ELSE 'Loyal'
    END AS customer_segment,
    COUNT(*) AS customer_count
FROM customer
GROUP BY customer_segment
ORDER BY customer_count DESC;


--Q8. What are the top 3 most purchased products within each category? 
SELECT
    category,
    item_purchased,
    purchase_count
FROM (
    SELECT
        category,
        item_purchased,
        COUNT(*) AS purchase_count,
        RANK() OVER (
            PARTITION BY category
            ORDER BY COUNT(*) DESC
        ) AS ranking
    FROM customer
    GROUP BY category, item_purchased
) AS ranked_products
WHERE ranking <= 3;

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT
    subscription_status,
    COUNT(*) AS customer_count
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;

--Q10. What is the revenue contribution of each age group? 
SELECT
    age_group,
    SUM("purchase_amount_(usd)") AS total_revenue
FROM (
    SELECT
        CASE
            WHEN age BETWEEN 18 AND 25 THEN '18-25'
            WHEN age BETWEEN 26 AND 35 THEN '26-35'
            WHEN age BETWEEN 36 AND 45 THEN '36-45'
            WHEN age BETWEEN 46 AND 55 THEN '46-55'
            WHEN age BETWEEN 56 AND 65 THEN '56-65'
            ELSE '66+'
        END AS age_group,
        "purchase_amount_(usd)"
    FROM customer
) AS t
GROUP BY age_group
ORDER BY total_revenue DESC;
